### PR TITLE
Pagination Options on Search

### PR DESCRIPTION
**Pull request by eileen-nava**
Issue: [Enable users to customize how many reports display on /form/view](https://github.com/usdoj-crt/crt-portal-management/issues/1281#)

I am creating a draft PR in order to transfer my work to @billyhunt.  This work is mostly done, however, it still needs styling in order to match the associated design.

Update to work.  To test, 

+ [ ] Click the Kabob menu above the right side of the table at /form/view
image

+ [ ] Try selecting different page sizes, and check the number of records that are returned. 

image

### CODE REVIEW

**Review by JackRyan1989 — CHANGES_REQUESTED** [review]
@billyhunt I'm seeing a slight display issue in Firefox only. 
Screen Shot 2022-08-05 at 4 38 04 PM

You can see that a little bit of the text in the first option element is appearing. I think you can fix this by increasing the padding to 1.2rem in this rule: `.usa-combo-box__input, .usa-input, .usa-input-group, .usa-range, .usa-select, .usa-textarea`

Looks like that rule is set in _border.scss, and it will affect the Personal Description input box as well. So maybe make a new rule for just this box?

**Comment by billyhunt** [comment]
> @billyhunt I'm seeing a slight display issue in Firefox only. Screen Shot 2022-08-05 at 4 38 04 PM
> 
> You can see that a little bit of the text in the first option element is appearing. I think you can fix this by increasing the padding to 1.2rem in this rule: `.usa-combo-box__input, .usa-input, .usa-input-group, .usa-range, .usa-select, .usa-textarea`
> 
> Looks like that rule is set in _border.scss, and it will affect the Personal Description input box as well. So maybe make a new rule for just this box?

I am not seeing this.  Can you let me know the browser and window size?

**Comment by billyhunt** [comment]
I don't think we need to worry about firefox here, as this is an internal tool and is only used on edge.

**Review by ilodidoj — CHANGES_REQUESTED** [review]
@billyhunt CI/CD showing failed tests. crt_portal/cts_forms/tests/test_views.py", line 395, in test_total_pages
    self.assertTrue(f'{num_records} of {num_records} records' in self.content). Please check this test on local docker test before pushing or merging to dev.

**Comment by JackRyan1989** [comment]
> I don't think we need to worry about firefox here, as this is an internal tool and is only used on edge.

Ok cool. It looks ok on everything except Firefox.

**Comment by billyhunt** [comment]
@ilodidoj and @JackRyan1989 Do we feel like this is ready to go?  If so can you mark it as such?

**Review by JackRyan1989 — APPROVED** [review]
I'm ok with approving this

**Comment by ilodidoj** [comment]
@billyhunt @JackRyan1989 doing local testing, update this in a few min.

**Comment by ilodidoj** [comment]
@billyhunt according to design handoff should there be option to view 100 records as well? If so, please add that to per_page html.  CC: @JackRyan1989

**Comment by billyhunt** [comment]
@ilodidoj We decided against that to start, as it could really bog the system down.

**Review by ilodidoj — APPROVED** [review]

**Review by ilodidoj — APPROVED** [review]
LGTM

**Pull request merged**
