### PR TITLE
Small refactor of complaint viewer filter JS code

### PR DESCRIPTION
**Pull request by el-mapache**
## What does this change?

Removes duplication and cleans up some of the code around building a new query string of filters based on existing filter query parameters in the URL and user interaction with filtering form controls on the `/form/view` intake page.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
If I am understanding correctly, this will eliminate the need for creating the filter lists in the python view since it is parsing the query from to url. I would like to remove any unused code from there.

I am also feeling like we have hit the point where we need some js tests for this. @el-mapache do you have any feelings on this?

I haven't looked at this code before so I am still reading it over and testing.

**Comment by el-mapache** [comment]
@LindsayYoung I don't think we need to remove any python code, this code just formats the form data into the query params that django needs to read. Testing seems like a good idea, but at the moment I'm not sure how much work it will be to introduce them. Additionally, we really only have 1-2 files that would benefit from it at this point (this one and the word count functionality). 

Also, I'm happy to go over any of the code with you!

**Comment by LindsayYoung** [comment]
@el-mapache I am having an issue locally where it is taking off the last filter instead of the filter I clicked. 

Add all the filters. Try to remove ADM, then you VOT is removed instead. Does this happen to you?

**Comment by el-mapache** [comment]
@LindsayYoung Yep, looks like a regression from the merge. It's a quick fix

**Pull request merged**
