### PR TITLE
Update python buildpack to 3.11.6

### PR DESCRIPTION
**Pull request by ilodidoj**
[Link to the issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1649)

## What does this change?
Update python buildpack to 3.11.6

## Checklist:
Log show new Pipfile and buildpack applied

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by ilodidoj** [comment]
@kewitham @okkays please check the python buildpack update PR. I will merge this once approved.  You probably need to rebase some of your previous PR with Dev after this buildpack PR merge.

**Comment by okkays** [comment]
@ilodidoj I need to update `jupyterhub/` as well - will push a change in a moment

**Review by okkays — APPROVED** [review]
LGTM (added update to `jupyterhub/Pipfile`, as well)

**Comment by ilodidoj** [comment]
> @ilodidoj I need to update `jupyterhub/` as well - will push a change in a moment

@okkays good catch. totally forgot about that part.  I have to remember that next time.

**Pull request merged**
