### PR TITLE
added footer back to hate crime modal form page

### PR DESCRIPTION
**Pull request by ilodidoj**
[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/917)

## What does this change?
added footer back to the hate crime form page.
## Screenshots (for front-end PR):
image

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by timoballard — CHANGES_REQUESTED** [review]
Looks good @ilodidoj!

What do you think about extending our playwright tests (`report_submission`) to check for the presence of the footer + privacy policy on the hate crime page?

**Comment by ilodidoj** [comment]
> Looks good @ilodidoj!
> 
> What do you think about extending our playwright tests (`report_submission`) to check for the presence of the footer + privacy policy on the hate crime page?

@timoballard That is a great idea, thanks.  I can take on this tomorrow, should it be separate card or merge this after the playwright test incorporated?

**Comment by timoballard** [comment]
@ilodidoj - We can make it part of this PR and merge after 👍

**Review by timoballard — APPROVED** [review]
Thanks @ilodidoj!

**Pull request merged**
