### PR TITLE
Fix HTML validation errors

### PR DESCRIPTION
**Pull request by el-mapache**
## What does this change?
Quick little PR to fix some HTML validation issues!

* Removes an extra `div` from the usa-banner
* Moves usa-banner into its own set of partials for easier readability
* Move `base.html` into top level templates folder to improve organization
* Removes unneeded `contentrole` attr from `footer
* Removes unneeded `label` attr from next button `input` node
* Moves `script` tags into the body

### CODE REVIEW

**Comment by LindsayYoung** [comment]
I think keeping the form base separate from the base will be helpful as we add different types of pages soon. It's not a dealbreaker, just wanted to note it

**Comment by el-mapache** [comment]
@LindsayYoung I'm not sure I follow, I think there is still a distinction between the pages with `base` and `report_base`. Are you saying that this PR could go father in abstracting the `base` content from the more form-specific content in `report_base`?

**Comment by LindsayYoung** [comment]
Ah, thank you! I think I just got confused with the re-name.

**Comment by LindsayYoung** [comment]
@el-mapache do you mind resolving the merge conflict? I want to make sure things get moved to the right place

**Comment by el-mapache** [comment]
@LindsayYoung All fixed up!

**Pull request merged**
