### PR TITLE
Make proform require 1900 as a minimum for incident year

### PR DESCRIPTION
**Pull request by eileen-nava**
[Fix minimum date for last_incident_year for proform](https://github.com/usdoj-crt/crt-portal-management/issues/1354)

## What does this change?
Previously, while filling out the proform, intake specialists could enter an incident year prior to 1900.  @JackRyan1989 noted this bug in his review of #1213.  I added a validation that prevents intake specialists from entering an incident year prior to 1900.

## Screenshots (for front-end PR):
IncidentYearValidation

## Checklist:
+ [ ] Submit a pro form with an incident date prior to 1900.  Observe the error.

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by eileen-nava** [comment]
@billyhunt Thanks for catching this!  I know what is wrong and I will fix it on Monday.

**Comment by eileen-nava** [comment]
Update: I fixed the bug that Billy found and added additional tests to catch the bug.  This PR is ready for another look.

**Review by ilodidoj — CHANGES_REQUESTED** [review]
@eileen-nava "When this happened" aka date of incident can remain blank but if user have input on any of the month, day, year all these should individually check I suppose.  I was able to enter 99/99/7000 locally. We probably should check for these fields when these has input and not blank.

**Comment by eileen-nava** [comment]
@ilodidoj I made the changes you requested.

**Review by ilodidoj — APPROVED** [review]
Validated locally, working as expected.  Great work @eileen-nava !

**Comment by ilodidoj** [comment]
@eileen-nava you can merge this to dev. Just approved.

**Pull request merged**
