### PR TITLE
[WIP]Mobile headings 617

### PR DESCRIPTION
**Pull request by hakhalid11**
[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/617)

## What does this change?
This adds correct mobile headings based on design audit findings.
### Author:

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by cantsin** [comment]
@hakhalid11 seems we have some merge conflicts here, can we fix? Also does this build on top of previous PRs?

**Comment by hakhalid11** [comment]
@cantsin Merge conflict resolved

**Comment by hbillings** [comment]
It looks like this is building off of #589, so I'm having a hard time reviewing it. If we can wait until that one gets merged, this one should be much more straightforward! I also[ left a comment on the original issue](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/617#issuecomment-665343633) clarifying some of the requested text changes, as the values I'm seeing in the original content _seem_ like they're the right ones.

**Comment by cantsin** [comment]
Revisiting this -- I'm a bit confused about where this PR is, I don't think this PR is ready for review just yet. Can we mark as WIP in the interim, at least until we get #589 in?

**Comment by Jkrzy** [comment]
@hakhalid11, what's the status of this?

**Comment by hakhalid11** [comment]
I agree with James, this should be WIP at the very least until 618 gets approved

**Pull request closed without merging**
