### PR TITLE
fix(combo-box): patch for z-index conflict

### PR DESCRIPTION
**Pull request by louh**
## What does this change?

Bug fix (reported by @billyhunt) for an issue with the combo box component where its child UI elements can appear on top of other site UI, e.g. in this case where the "Assigned to" select UI shows above the "Contact complainant" modal.

Screen Shot 2021-11-10 at 11 42 07 AM

The fix is to apply a z-index to the parent `.usa--combo-box` element which creates a local "stacking context" that keeps the child elements from leaking into the global stacking context.

## Screenshots (for front-end PR):

Should look like this, post-fix.

Screen Shot 2021-11-10 at 11 42 14 AM

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by billyhunt — APPROVED** [review]
Works as intended on both the dashboard and the view pages.

**Comment by louh** [comment]
Just leaving a note for myself - I looked into whether this change is worth patching upstream on USWDS, and it actually introduces another problem if there is another combo-box (or generically speaking, another stacking context) below this one: making the button UI not appear other elements can then cause the dropdown to not properly appear over other UI. We don't have that problem here, but it could also mean that (a) we would need to find a follow-up solution in case it does become a problem, or (b) we still need to see if a different solution could be found in a future update to USWDS. I'll open that conversation there too.

**Comment by billyhunt** [comment]
Good work!

**Comment by louh** [comment]
@billyhunt I'm going to close this in favor of #1038, where I have to make a few changes to the "assigned to" UI anyway (https://github.com/usdoj-crt/crt-portal-management/issues/1140), and I'm going to address this in the modal z-index rather than the combo box z-index.

**Pull request closed without merging**
