### PR TITLE
Update uswds@2.5.1

### PR DESCRIPTION
**Pull request by louh**
## What does this change?

This updates our use of the US Web Design System (USWDS) to [version 2.5.1](https://github.com/uswds/uswds/releases/tag/v2.5.1), including updating the `uswds-gulp` dependency. This upgrade process is described in https://github.com/usdoj-crt/crt-portal-management/issues/1023 and is part of https://github.com/usdoj-crt/crt-portal-management/issues/1012.

Each update to USWDS was applied step-by-step to make sure we are adopting changes that apply to our project. Here is a run-down of changes that affected us:

- [2.1.0](https://github.com/uswds/uswds/releases/tag/v2.1.0)
  - No changes.
- [2.2.0](https://github.com/uswds/uswds/releases/tag/v2.2.0), [2.2.1](https://github.com/uswds/uswds/releases/tag/v2.2.1)
  - Removes manual ARIA role on the `nav` element, as this is redundant in modern HTML 5.
  - Adds new theme setting variables.
  - Renames two theme setting variables.
- [2.3.0](https://github.com/uswds/uswds/releases/tag/v2.3.0)
  - Add import of 'uswds-theme-components'
  - Update setting variables.
- [2.4.0](https://github.com/uswds/uswds/releases/tag/v2.4.0)
  - Add the new notifications setting variable.
  - This update introduces a change to font family in the page header, which is also fixed.
  - Update to corresponding [uswds-gulp](https://github.com/uswds/uswds-gulp).
- [2.5.0](https://github.com/uswds/uswds/releases/tag/v2.5.0), [2.5.1](https://github.com/uswds/uswds/releases/tag/v2.5.1)
  - Update to canonical Dart Sass compiler. We remove the deprecated node-sass dependency.
  - Incorporate changes to `gulpfile.js`.
  - Fix a deprecated behavior that came from `@extend`ing a compound selector in our stylesheet.
  - Updated accessibility markup to `banner` and `footer` components.

## Screenshots (for front-end PR):

image

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by louh** [comment]
Please note that this PR formerly stopped at `uswds@2.4.0` and has now been updated to include all updates up to `uswds@2.5.1`.

**Review by billyhunt — APPROVED** [review]
Looks good to me.  Tests pass and site looks good.  We might want to get Bill to give it a solid once over when its in dev to make sure any css did not get weird.

**Review by ilodidoj — COMMENTED** [review]
@louh and @billyhunt I am seeing two commas within the area label value > aria-label="Official government website**,,**"
Not sure that is part of the new syntax or unintended addition during edit.  If this impose no issue I can merge the PR.

**Comment by louh** [comment]
@ilodidoj The commas are intentional and I'm glad you noticed it. From what I can tell, screen readers will pause when they encounter a period or a comma. Two commas seems to be a way to introduce a longer pause.

I couldn't find any guidance on whether it's "best" to use two commas, none, or any number of them, but the US Web Design System website uses two commas on their own site:

Screenshot 2021-08-19 13 31 27

So I just decided to follow their lead.

We can remove it, but leaving it in won't pose any problems.

**Comment by ilodidoj** [comment]
@louh please see the branch conflicts which need to be resolved. CC: @billyhunt

**Comment by louh** [comment]
@ilodidoj This is currently blocked because a dependency change in a previous PR is now causing the CSS build pipeline to fail in this one. I will investigate this today and update you when it's ready to review again.

**Comment by ilodidoj** [comment]
> @ilodidoj This is currently blocked because a dependency change in a previous PR is now causing the CSS build pipeline to fail in this one. I will investigate this today and update you when it's ready to review again.

Thank you. Appreciated. :)

**Comment by louh** [comment]
@ilodidoj Finally was able to fix the conflict. This should be set to go!

**Pull request merged**
