### PR TITLE
Il/pol outgoing response language 1195

### PR DESCRIPTION
**Pull request by ilodidoj**
[Link to issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1195)

## What does this change?
POL section form letter dropdown available in Spanish, Simplified Chinese, Traditional Chinese, Vietnamese, Tagalog and Korean.

## Checklist:
Policy section displayed on form letter subject:
  Go to report detail assigned to POL section
  Select contact complainant button
  Select any language
  Subject line displayed with Policy Section in respective to language selection.

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by ilodidoj** [comment]
@louh @billyhunt ready for PR review.  Please specifically check the Traditional and Simplified Chinese both translation in supplied looked same to me. Vietnamese probably needed 'Ban' along with supplied translation.

**Comment by louh** [comment]
I can validate that it works but I also want confirmation that the Traditional and Simplified Chinese translations are supposed to use the same characters - that's unusual.

**Comment by ilodidoj** [comment]
@louh i am checking with Bill L. for final confirmation on the language.

**Comment by ilodidoj** [comment]
@louh Bill confirmed the current translation is the final one. Please approve the PR.

**Review by louh — APPROVED** [review]

**Pull request merged**
