### PR TITLE
HCE form letter translations

### PR DESCRIPTION
**Pull request by JackRyan1989**
[Link to ZenHub issue.](link-goes-here)

## What does this change?

Added following translations for the HCE Form Letter:
1. Vietnamese: https://github.com/usdoj-crt/crt-portal-management/issues/1239
2. Tagalog: https://github.com/usdoj-crt/crt-portal-management/issues/1241
3. Korean: https://github.com/usdoj-crt/crt-portal-management/issues/1246
4. Traditional Chinese https://github.com/usdoj-crt/crt-portal-management/issues/1237
5. Simplified Chinese: https://github.com/usdoj-crt/crt-portal-management/issues/1238

## Checklist:

- [x] Confirm that translations appear on form/views page when contacting recipient
- [x] Confirm that links in translations all work
- [x] Confirm that printing does not alter the content 

+ [x] Vietnamese: https://github.com/usdoj-crt/crt-portal-management/issues/1239
+ [x] Tagalog: https://github.com/usdoj-crt/crt-portal-management/issues/1241
+ [x] Korean: https://github.com/usdoj-crt/crt-portal-management/issues/1246
+ [x] Traditional Chinese https://github.com/usdoj-crt/crt-portal-management/issues/1237
+ [x] Simplified Chinese: https://github.com/usdoj-crt/crt-portal-management/issues/1238

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by ilodidoj — COMMENTED** [review]
@billyhunt @JackRyan1989  Contact Complainant dropdown showing TEST items first, should be last in the order, e.g. in dev env.  I am seeing in my local dev.  Not sure the update and new entry reset the original order of the drop down.

**Comment by ilodidoj** [comment]
@billyhunt Spanish version of the letter does not format for bullets and URL link. All others are OK.

**Comment by billyhunt** [comment]
I don't think that one was a PR (did we do spanish a while ago?), but I will update!

**Comment by ilodidoj** [comment]
> 

@billyhunt your are correct that was not in the PR, we probably did this a while ago.  Please check the dropdown order, validate in your local to match current dev/prod version of the drop down order.  I can then approve the PR.

**Comment by billyhunt** [comment]
Should we just delete those test response templates?  We don't really need them anymore.

**Comment by ilodidoj** [comment]
> Should we just delete those test response templates? We don't really need them anymore.

@billyhunt , I want to get product teams input first, then we should create a separate card for remove delete of any items, i.e. TEST form templates here.

**Comment by billyhunt** [comment]
Maybe we should wait until Monday then to finish this PR then.  I think deleting them is a good idea, (we didn't do it earlier because we wanted some practice creating html templates.  This has happened).  I would rather get rid of them than reorder, with the potential of causing more trouble.

**Review by ilodidoj — APPROVED** [review]
@billyhunt I am approving these changes, validated locally and working as expected.  I will merge these to dev as well.  Please create a separate card and code PR for deleting or removing the TEST letters.

**Pull request merged**
