### PR TITLE
Day 1 of spike on internationalization with @el-mapache

### PR DESCRIPTION
**Pull request by alexsoble**
[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/152)

## What does this change?

This is the work product of the first day of a 2-day `i18n` spike with @el-mapache.

In this PR, we got the fundamentals of the Django i18n system working — defining a translation file with a few fake-translated strings, and getting Django to surface those fake translations to a user.

### What's next?

There's still more to do — next, we'll work on telling Django to translate strings that are stored in the JavaScript code and in the database. And of course setting a user's language preference (through a dropdown menu or browser preferences) is a separate topic. As much as we get done in this 2-day time-boxed spike, we get done.

## How to test this PR

1. In `settings.py`, change the value of `LANGUAGE_CODE` from `en-us` to `es`.
2. Navigate to the `es` `django.po` file:  `crt_portal/cts_forms/locale/es/LC_MESSAGES/django.po`.
3. Change the value of `msgstr` for one of the strings you'd like to translate — supply any test value you like (pseudolocalization testing). 
4. Run `docker-compose run web django-admin compilemessages`.
5. Start the site locally and navigate to a page that contains the translated content to see your fake test translation value. 

## Screenshots (for front-end PR):

Fake pseudolocalization for "Next" button: 

translation-screenshot

### Author

+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### CODE REVIEW

**Comment by alexsoble** [comment]
☝️ Paired on these commits with @el-mapache!

**Comment by alexsoble** [comment]
Hmmmmm, I think I fumbled merging upstream changes to the README. Will take a look tomorrow, fix any mistakes, and submit for PR review.

**Comment by alexsoble** [comment]
I thought I had made a mistake fixing merge conflicts in the README, because the generate-front-end step mentions `nvm install` twice. But looks like that's present in the README on `develop` as well, so not something that needs to be fixed by this PR.

**Comment by alexsoble** [comment]
Updated the PR body with more context and instructions for how to test this PR; this should now be ready for review!

**Comment by alexsoble** [comment]
Merging in #167 for a consolidated review.

**Comment by LindsayYoung** [comment]
This looks like a great spike! I think we understand what is easy to implement and what we need to do more research on. 

Let's  talk about if we want to merge this, or keep it for future reference. One thing that that makes me think we might want to keep this for reference rather than merge, is having half of `forms.py` and `model-variables.py` being formatted differently. If we do want to merge, let's see if we can prioritize consistently adding the `_(` text.. `)` format to all the strings we have that will need to be translated and keep that consistency going forward.

**Comment by alexsoble** [comment]
I am strongly in favor of merging this in the spirit of incremental progress. Creating the pathway for i18n through changes to the Dockerfile, README, and .po/.mo files feels like concrete, forward-momentum work to me; marking every string in the codebase for translation can be a separate chunk of work. 

Some of the strings in `model_variables.py` are not marked for translation because they are stored in the database and we'll need either a refactor, a library, or both to get them to internationalize correctly. I think it's OK if we conceptualize that as a separate chunk of work.

**Pull request merged**
