### PR TITLE
Change minimum date for externally submitted report

### PR DESCRIPTION
**Pull request by eileen-nava**
[Fix minimum date for report submission.](https://github.com/usdoj-crt/crt-portal-management/issues/1352)

## What does this change?
Previously, although the external-facing report submission process was only supposed to allow reports for events that had occurred in 1900 or later, users could enter December 31, 1899 for the event date.  This contradicted [validation error messages](https://github.com/usdoj-crt/crt-portal/blob/develop/crt_portal/cts_forms/model_variables.py#L452).  I did some code archaeology and found [the original PR](https://github.com/usdoj-crt/crt-portal/pull/246) that allowed December 31, 1899 as an event date.  I didn't see any justification for allowing this date, so I changed the cut-off to January 1, 1900.

## Screenshots (for front-end PR):
BEFORE
A report could be submitted with the December 31, 1899 date
ReportDec311899

AFTER
A report could not be submitted with the December 31, 1899 date
Screen Shot 2022-07-13 at 1 41 27 PM

## Checklist:
+ [ ] Attempt to submit a report with December 31, 1899 as the event date.  Confirm the resulting error message exists.

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by JackRyan1989 — COMMENTED** [review]
@eileen-nava The validation works on the user facing front end. However, someone working on the Admin side of the portal can enter a date before 1900. I was able to create a report from the /form/view/ endpoint with the date of 12/31/1899. See screen shot as proof:

Screen Shot 2022-07-13 at 2 53 52 PM

**Comment by billyhunt** [comment]
Seeing Jack's note now.  I guess look into that first, see if the scope needs to be expanded.

**Comment by ilodidoj** [comment]
@billyhunt @eileen-nava @JackRyan1989 instead of expanding the scope, please open a new PR for Intake and pro form date fix update from the development branch.  These are same issue but isolated tasks.

**Review by JackRyan1989 — APPROVED** [review]

**Comment by eileen-nava** [comment]
I will merge this PR now and open a new PR for the pro form fix.  Thanks for the feedback. 👍🏻

**Pull request merged**
