### PR TITLE
Show last form letter sent on total complaints activity column

### PR DESCRIPTION
**Pull request by louh**
[Link to issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1077)

## What does this change?

Adds a new column to the "total complaints activity" widget that shows whether a form letter was sent, and includes a hover interaction to display the name of the form letter template.

This implementation uses activity data that's already cached on the report. Theoretically we avoid a new database join or call with this implementation.

## Screenshots (for front-end PR):

**Baseline UI state:**

Screen Shot 2021-09-23 at 3 15 06 PM

- Left and right whitespace removed which gives a little more breathing room to the data.
- We have the space to display the full "Letter sent" label from the mockup, so I've included it here. Let me know if anyone prefers it to be removed.
- I'm also using the question-mark-in-circle icon from the mockup, but we can also switch that out for the e-mail icon easily.

**Hover UI state:**

Screen Shot 2021-09-23 at 3 15 10 PM

- Tooltips use the component from [the US Web Design System](https://designsystem.digital.gov/components/tooltip/), so we are not rebuilding functionality and accessibility from scratch.
    - Note: We didn't update the static JS bundles that come with each version of the USWDS previously. This has been updated here so we could pull in the tooltip JavaScript code.
- I prefer the dark tooltip (mockup no. 1)
- I made the entire label ("letter sent" + icon) accept the hover interaction, otherwise the icon alone has a very small hit box and is much harder to interact with.

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by ilodidoj — COMMENTED** [review]
my local test is failing. Please see if you able to run local test: docker-compose run web python /code/crt_portal/manage.py test cts_forms --parallel. @louh please update the checkbox on PR for author after task completed.

**Review by ilodidoj — APPROVED** [review]

**Comment by louh** [comment]
@ilodidoj I can confirm local tests are also not working on my end, I'll investigate this today.

**Comment by ilodidoj** [comment]
I think this is related to update of USWDS 2.8.x . Since the send buttons are not working on the modal, therefore test will fail. Note, current dev has both this and USDS2.8.x fixes therefore, test pass in Circle Ci.

**Comment by louh** [comment]
@ilodidoj See the issue I just created (https://github.com/usdoj-crt/crt-portal-management/issues/1082). I've run tests on each commit to narrow down the cause, and it's not related to updating USWDS 2.8.x. It is specifically caused by the commit that implemented email activity on the total complaints widget.

**Pull request merged**
