### PR TITLE
Fix TMS admin template.

### PR DESCRIPTION
**Pull request by okkays**
## What does this change?

- 🌎 The TMS admin view shows admin details
- ⛔ Right now it's not, though, because it's using the wrong template.
- ✅ This commit fixes the template
- 🔮 Future commits will provide any additional fixes that are needed once we see how this behaves in prod.

## Screenshots (for front-end PR):

image

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by kewitham — CHANGES_REQUESTED** [review]
Do we still need to use email.html in the api views.py and mail.py files?

**Comment by okkays** [comment]
> Do we still need to use email.html in the api views.py and mail.py files?

Yes - that's a different `email.html`. Previously we had both:

```
crt_portal/cts_forms/templates/email.html
crt_portal/templates/email.html
```

Django could only ever find one of them, which caused the bug that this PR fixes.

**Comment by ilodidoj** [comment]
> > Do we still need to use email.html in the api views.py and mail.py files?
> 
> Yes - that's a different `email.html`. Previously we had both:
> 
> ```
> crt_portal/cts_forms/templates/email.html
> crt_portal/templates/email.html
> ```
> 
> Django could only ever find one of them, which caused the bug that this PR fixes.

@okkays @kewitham If we currently using HTML version for auto reply, then, please check if any impact with this changes and update both auto reply and manual HTML reply accordingly.

**Comment by okkays** [comment]
@ilodidoj @kewitham these changes only affect the TMS admin page template.

They don't affect user-facing emails.

The two templates had the same name which was confusing to both us and Django - but they take different context variables and are used in separate views. This renames the TMS admin template, and leaves the user email template alone.

**Pull request merged**
