### PR TITLE
Added test cases for complaint actions form

### PR DESCRIPTION
**Pull request by kmanubhai**
Currently working on Resolving to Merge Conflict

[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/713)

## What does this change?
Unit test for Complaint.Action.testcase.test, Smaller change of code in test_forms.py

## Checklist:
ran tests with changes multiple times

### Author
kmanubhai

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] Check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by kmanubhai** [comment]
James Save me here, Please!!!

**Comment by cantsin** [comment]
@kmanubhai what do you need help with here?

**Comment by cantsin** [comment]
@kmanubhai ah, okay! I mentioned this on slack, but I think rebasing onto develop is the easiest solution here, given that your PR is one commit. but really, there's a few ways to fix this merge conflict, any will do. my suggested method:

```sh
git fetch --all # get updated references
git rebase origin/develop 
```

let me know if that doesn't work?

**Comment by kmanubhai** [comment]
> @kmanubhai ah, okay! I mentioned this on slack, but I think rebasing onto develop is the easiest solution here, given that your PR is one commit. but really, there's a few ways to fix this merge conflict, any will do. my suggested method:
> 
> ```shell
> git fetch --all # get updated references
> git rebase origin/develop 
> ```
> 
> let me know if that doesn't work?

Tanks James, will keep you posted.

**Comment by kmanubhai** [comment]
Hey James,

                 I just executed commands again, do you want me to create another pull request to see changes or it should reflect automatically ?

[cid:f052b01b-ff40-4820-9627-d7a8cbce8728]
________________________________

**Comment by cantsin** [comment]
@kmanubhai after a rebase you will need to force a push to your branch. that will update this PR automatically, yes. (but please make sure the PR looks good by doing a `git diff origin/develop` first.)

**Comment by kmanubhai** [comment]
I tried rebase but it did not work, so i created the new branch for this and closing this pull request.

**Pull request closed without merging**
