### PR TITLE
Make notebooks embeddable in the portal

### PR DESCRIPTION
**Pull request by okkays**
[Link to issue](https://github.com/usdoj-crt/crt-portal-management/issues/1614)

See notes for reviewer for how to review, as the dashboard will be empty by default.

## What does this change?

- 🌎 Jupyter notebooks are only viewable from Jupyter / the admin panel
- ⛔ This isn't great, as we want to show them in the intake portion
- ✅ This commit makes them embeddable by defining dashboard groups, and adds "total_complaints" as an example dashboard.
- 🔮 Future commits will:
  - Allow filtering by section
  - Programatically create the dashboard configurations
  - Create more notebooks to embed!

## Screenshots (for front-end PR):

image

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

To create a dashboard and refresh the notebook output (this will all be done automatically in the future):

- [ ] Run `docker-compose run web python /code/crt_portal/manage.py update_ipynb_examples`
- [ ] Enable the "data-dashboard" feature
- [ ] Add a "Dashboard Group" from the admin panel, to make a place for the notebook to go
- [ ] Add a "FileGroupAssignment" from the admin panel, to pair the notebook with the group
- [ ] Re-run and save the notebook from Jupyter, so that the output appears
- [ ] View the dashboard by clicking "Data dashboard" from the intake sections!

GIF walkthroughs of the above:
1-enable-dashboard
2-add-group
3-add-assignment
4-rerun
5-profit

### CODE REVIEW

**Comment by okkays** [comment]
(sorry for the unassignment / reassignment - I'd found a bug in this PR)

**Review by kewitham — COMMENTED** [review]
I'm confused about what the interaction is supposed to be here. Should there be more sections listed for me to choose? When I click the plus sign to add more I can't select multiple either: 
image

**Comment by kewitham** [comment]
This might be user error but when I load the page I see this: 
image

**Comment by okkays** [comment]
> I'm confused about what the interaction is supposed to be here. Should there be more sections listed for me to choose? When I click the plus sign to add more I can't select multiple either:

You have to create the sections in your local development server if you haven't (these exist on dev / stage / prod)

> This might be user error but when I load the page I see this:

👀 will take a look!

**Review by kewitham — APPROVED** [review]
lgtm!

**Pull request merged**
