### PR TITLE
fix(styles): wrong hero image on mobile; extra bottom-border on footer in mobile

### PR DESCRIPTION
**Pull request by louh**
## What does this change?

This is a hotfix to the 09-07-2021 release branch (currently on staging) that fixes a regression where the hero element of the landing page has the wrong background image on mobile devices. As a result, the hero text has improper contrast with the background, and is not legible. This warrants a hotfix before deploying to production.

The regression was caused by a change in the CSS build process of `uswds-gulp` (see https://github.com/uswds/uswds-gulp/commit/b714fd93fe917618ac666bbe50a6fdf1fff6b88d), which no longer forces media queries to be re-sorted. This altered the priority in which certain media queries applied styles to different devices, and the mobile view has improperly used the background for tablet devices. I did not initially expect this build process change to affect our stylesheets, but it turns out that it did. We fix this issue by changing the source order of the affected media query so that the build output has styles in the expected priority order.

This hotfix also fixes a smaller, less destructive regression that caused a small white border to appear on the bottom of the footer, also only on mobile devices.

This pull request was made to fix the immediate issue before deploying to production; it is not intended to guard against future regressions of a similar nature. However, we do have CI tests that will fail if text has improper contrast with its background. My next step to follow up from this is to see whether these tests can be augmented to cover mobile views.

## Screenshots (for front-end PR):

Regression (current develop branch)

Screen Shot 2021-09-01 at 6 00 43 PM

Expected (fix)

Screen Shot 2021-09-01 at 6 05 43 PM

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by ilodidoj — APPROVED** [review]
Matches current production.

**Comment by ilodidoj** [comment]
@billyhunt Please review this PR and compare with current production https://civilrights.justice.gov/ in responsive and other mobile simulations. It should mach.  I have checked, but wanted to make sure it works on another device as same too.  I will merge to release after your PR approval. CC: @louh

**Review by billyhunt — APPROVED** [review]
Looks good.  Checked on Chrome, Safari, and Edge.

**Comment by ilodidoj** [comment]
> Looks good. Checked on Chrome, Safari, and Edge.

@billyhunt Thanks. I will merge the PR to the release now.

**Pull request merged**
