### PR TITLE
Referred report flag

### PR DESCRIPTION
**Pull request by cantsin**
[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/822)

## What does this change?

Adds a "Secondary Review" checkbox (nee "Referral") to report actions.

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by Jkrzy — APPROVED** [review]
Thanks @cantsin, looks good and nice test coverage!

**Review by Jkrzy — CHANGES_REQUESTED** [review]
Ah, in manual testing noticed that the Assignee autocomplete dropdown is rendering behind the new checkbox, obscuring the first `option`

Screen Shot 2020-12-21 at 10 53 08 AM

**Comment by Jkrzy** [comment]
@timoballard, I tackled the change request above -- can you code review that latest piece for this pr?

**Review by timoballard — APPROVED** [review]
Looks good! Verified the activity stream, CSV export, and dropdown rendering addressed by @Jkrzy

**Comment by Jkrzy** [comment]
My attempted fix needs a closer look, it results in the autocomplete for `Assign to` rendering on top of any modals on the page. ☹️

**Comment by cantsin** [comment]
Sure, will look at this.

**Pull request merged**
