### PR TITLE
Update docs for adding new language

### PR DESCRIPTION
**Pull request by timoballard**
[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/902)

## What does this change?
Updates our documentation to include instructions for adding support for a new language. 

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by ilodidoj** [comment]
Little more guidance needed on "Language" meta data. Where one should look for actual meta data apply to specific language? 
Suggestions for new-language-translations.xlsx and updated.po file to created and kept out of app base location, e.g. under tmp or some other directory.  These files are not directly related to source code and not intended commit to the git.

**Comment by ilodidoj** [comment]
some guidance also needed on where to find the language related information to change these in .PO file 
"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"

**Comment by timoballard** [comment]
Thanks for the feedback @ilodidoj - just pushed updates

**Review by ilodidoj — APPROVED** [review]
LGTM

**Pull request merged**
