### PR TITLE
Only run the memory intensive distinct search when needed. 

### PR DESCRIPTION
**Pull request by billyhunt**
[Link to ZenHub issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1274)

## What does this change?

the .dintinct() DB search is adding some memory constraints on our already taxed DB.  We only need to run it if we are searching through multiple reported_reasons, which is not the majority of searches.

NOTE: we might want to hotfix this into production, especially if we cannot improve the DB size quickly. 

## Screenshots (for front-end PR):

+ [x] Make sure searches work with no reported reason EG http://localhost:8000/form/view/?status=new&status=open&status=closed&no_status=false
+ [x] Make sure searches work with one reported reason EG http://localhost:8000/form/view/?status=new&status=open&status=closed&reported_reason=age&no_status=false
+ [x] Make sure searches work with multiple reported reasons EG http://localhost:8000/form/view/?status=new&status=open&status=closed&reported_reason=age&reported_reason=disability&reported_reason=family_status&reported_reason=gender&reported_reason=genetic&reported_reason=immigration&reported_reason=language&reported_reason=national_origin&reported_reason=pregnancy&reported_reason=race%2Fcolor&reported_reason=religion&reported_reason=sex&reported_reason=orientation&reported_reason=none&reported_reason=other&no_status=false

You might check the SQL time length.  

Before:
image

After
image

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by JackRyan1989 — APPROVED** [review]
So this change seems super straightforward, and the search is clearly faster with only one reported reason vs. multiple reasons. From my testing, single reasons seemed to take on average 1400 ms. Whereas multiple reported reasons took about 2200 ms. Which is inline with the screenshots.

Question: I'm surprised by the behavior of the "None of these apply to me", should that remove all of the other reasons selected if it's checked?

**Review by eileen-nava — APPROVED** [review]
Looks rad to me. 🥕 🎸

**Comment by billyhunt** [comment]
"Question: I'm surprised by the behavior of the "None of these apply to me", should that remove all of the other reasons selected if it's checked?"

That sounds right to me.  Chinelo what do you think?

**Comment by chinelo-ikejimba** [comment]
> "Question: I'm surprised by the behavior of the "None of these apply to me", should that remove all of the other reasons selected if it's checked?"
> 
> That sounds right to me. Chinelo what do you think?

@JackRyan1989 @billyhunt  @eileen-nava @ilodidoj 

Agreed! The expected behavior would be that "none of these apply to me" remove all the other reasons.

**Pull request merged**
