### PR TITLE
Vietnamese

### PR DESCRIPTION
**Pull request by timoballard**
[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/205)

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by Jkrzy — COMMENTED** [review]
Looking great! 

I noticed we're not translating the `Print Report` button in `confirmation.html`. That applies here and across _all_ languages.

**Comment by Jkrzy** [comment]
A few layout tweaks we should add to the backlog for remediation:
Language select button
Screen Shot 2021-04-09 at 12 28 41 PM

Report Location city/state:
Screen Shot 2021-04-09 at 2 15 23 PM

**Review by Jkrzy — APPROVED** [review]
Thanks @timoballard, this looks good except for the missing `Print Report` translation and the bit of positioning that I'd recommend we tackle in a separate issue.

**Comment by timoballard** [comment]
[Card 924](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/924) created to capture `Print report` translation work

**Comment by timoballard** [comment]
Resolved hate crime response translation in 5fe5f427a95f5be23eebad29312c20d3b0229085.

Collecting layout/alignment issues [here](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/925) for later remediation.

**Pull request merged**
