### PR TITLE
Bump clamav RAM and versions

### PR DESCRIPTION
**Pull request by okkays**
## What does this change?

Upgrade RAM for clamAV to prevent failures.

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by ilodidoj** [comment]
@okkays let's update the docker version of the ClamAV to latest as well.

**Comment by okkays** [comment]
@ilodidoj done!

**Comment by ilodidoj** [comment]
@okkays I was getting connection refused on my local docker on MAC.  I tried to resolve this by adding following to the docker compose file for the ClamAV section.  Please check if you scan a file on local docker instance without this port configurations:
restart: unless-stopped
    ports:
      - "3310:3310"
      - "9000:9000"

**Comment by okkays** [comment]
> @okkays I was getting connection refused on my local docker on MAC. I tried to resolve this by adding following to the docker compose file for the ClamAV section. Please check if you scan a file on local docker instance without this port configurations: restart: unless-stopped ports: - "3310:3310" - "9000:9000"

I can scan successfully without those.

Binding ports in docker-compose.yml will cause the standalone instances to fail; local ports are specified in docker-compose.override.yml. You can confirm the ports are working (only 9000 needs to be exposed) by running `docker compose config`

I'd like to know what is causing your local instance to fail to require the `restart: unless-stopped`. Mine runs fine on the first go, is there anything interesting in your `docker compose logs clamav-rest`?

**Review by ilodidoj — APPROVED** [review]
@okkays if your local docker working without specific port mentioned, this can be merged. I was getting connection refuse and timed out for both 3010 and 9000. Since this local issue, code can be merged to dev.

**Pull request merged**
