### PR TITLE
Replace autocomplete library

### PR DESCRIPTION
**Pull request by cantsin**
[Link to ZenHub issue.](https://app.zenhub.com/workspaces/doj-crt-intake-scrum-board-5d03bf56c1c8a35d482eca0f/issues/18f/crt-portal/712)

## What does this change?

Replaces previous autocomplete library which was causing us issues (breaks on specific versions of Edge and requires code workarounds).

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [x] Check for [accessibility](/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] Re-check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by cantsin** [comment]
@Jkrzy before I continue working on this I wanted to confirm that this library seems like a good replacement. Note that delete works the same way as before, e.g., user has to click elsewhere (to activate the blur event) to actually unset the value. Other than this behavior (which the previous auto complete also had), curious as to your thoughts.

**Comment by Jkrzy** [comment]
After looking at the small implementation you've already done and running through some quick functionality checks in edge and w/ VoiceOver -- 👍 this looks to be a reasonable replacement.

I know we looked at a few other options, as a separate effort I'd love to chat a bit more about them with an eye towards documenting our choice a bit more for others to build upon.  

Thanks @cantsin!!

**Comment by cantsin** [comment]
Alright, I fixed the last of the (oh-so fiddly) SCSS issues. Let me know if there's anything amiss. @timoballard would love your :eyes: on this one too as this is a replacement for the older library which caused us some grief. Don't forget to test on Edge. Thanks!

**Review by Jkrzy — APPROVED** [review]
Looks good to me, thanks @cantsin!

Will wait on @timoballard's review to merge.

**Review by timoballard — APPROVED** [review]
🚀

**Comment by cantsin** [comment]
Thanks y'all! Pushing this in, the more :eyes: we have on this the sooner, the better

**Pull request merged**
