### PR TITLE
feat(intake filters): add search help page

### PR DESCRIPTION
**Pull request by louh**
[Link to issue.](https://github.com/usdoj-crt/crt-portal-management/issues/1194)

## What does this change?

Adds a new page with examples of complex search queries.

## Screenshots (for front-end PR):

Screenshot 2022-02-23 at 11-48-04 Contact the Civil Rights Division Department of Justice

Screenshot 2022-02-23 at 11-15-51 Contact the Civil Rights Division Department of Justice

## Checklist:

+ [x] Verify that the help text on /form/view matches the mockup
+ [x] Create some search filters, then click "View search examples." Verify that help content matches the design mockup / intent.
+ [x] Click "Back to all" and verify that search filters are remembered.

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by chinelo-ikejimba** [comment]
@louh @billyhunt @ilodidoj - Can the advanced search operators get bolded in the example descriptions to emphasize how they affect the query like in the design mockup?

**Comment by louh** [comment]
@chinelo-ikejimba yes! Good catch, I had missed it in the mockup.

**Comment by louh** [comment]
Screenshot 2022-02-24 at 10-54-26 Contact the Civil Rights Division Department of Justice

**Comment by ilodidoj** [comment]
@louh @billyhunt I will be doing the PR review on this today.

**Review by ilodidoj — APPROVED** [review]
@louh verified locally, page displayed accordingly. LGTM. Please merge to dev.

**Comment by chinelo-ikejimba** [comment]
> Screenshot 2022-02-24 at 10-54-26 Contact the Civil Rights Division Department of Justice

@louh great job!

**Pull request merged**
