### PR TITLE
Remove localstack

### PR DESCRIPTION
**Pull request by kewitham**
[Issue #1625](https://github.com/usdoj-crt/crt-portal-management/issues/1625)

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [ ] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by okkays — APPROVED** [review]
I'm still seeing a couple of `localstack` mentions around the codebase, in documentation and one test:

```
└╼ ag -i local.?stack
crt_portal/crt_portal/settings.py
510:        # Allow for overriding settings (such as ports and localstack)

crt_portal/cts_forms/tests/test_views.py
327:            return self.skipTest('localstack is disabled, but attachments work')

README.md
422:Another way to have a speedier experience locally is to not run local stack and ClamAV unless you are testing attachment uploads or email.
```

once those are removed, LGTM! Runs locally after deleting / rebuilding my docker environment

@ilodidoj FYI, this drops localstack (there doesn't seem to be a great upgrade path without going beyond the free plan)

**Comment by ilodidoj** [comment]
> I'm still seeing a couple of `localstack` mentions around the codebase, in documentation and one test:
> 
> ```
> └╼ ag -i local.?stack
> crt_portal/crt_portal/settings.py
> 510:        # Allow for overriding settings (such as ports and localstack)
> 
> crt_portal/cts_forms/tests/test_views.py
> 327:            return self.skipTest('localstack is disabled, but attachments work')
> 
> README.md
> 422:Another way to have a speedier experience locally is to not run local stack and ClamAV unless you are testing attachment uploads or email.
> ```
> 
> once those are removed, LGTM! Runs locally after deleting / rebuilding my docker environment
> 
> @ilodidoj FYI, this drops localstack (there doesn't seem to be a great upgrade path without going beyond the free plan)

What should be our path forward for attachment and ClamAV testing for s3 bucket if we do not upgrade to pricing model for localstack?

**Comment by kewitham** [comment]
> > I'm still seeing a couple of `localstack` mentions around the codebase, in documentation and one test:
> > ```
> > └╼ ag -i local.?stack
> > crt_portal/crt_portal/settings.py
> > 510:        # Allow for overriding settings (such as ports and localstack)
> > 
> > crt_portal/cts_forms/tests/test_views.py
> > 327:            return self.skipTest('localstack is disabled, but attachments work')
> > 
> > README.md
> > 422:Another way to have a speedier experience locally is to not run local stack and ClamAV unless you are testing attachment uploads or email.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > once those are removed, LGTM! Runs locally after deleting / rebuilding my docker environment
> > @ilodidoj FYI, this drops localstack (there doesn't seem to be a great upgrade path without going beyond the free plan)
> 
> What should be our path forward for attachment and ClamAV testing for s3 bucket if we do not upgrade to pricing model for localstack?

We should still be able to test attachments without localstack, clamav scans the attachment before it is stored in the s3 bucket so now the attachment will just be scanned and then stored in the local file system instead. Kevin and I have noticed a bug with getting ClamAV to scan attachments locally (unrelated to this PR) that I'm currently looking into.

**Comment by ilodidoj** [comment]
@kewitham @okkays ajilaag/clamav-rest maintain more frequently than the one replaced with (7 years ago).  clamav rest version should be more frequently maintained one.

**Comment by kewitham** [comment]
> @kewitham @okkays ajilaag/clamav-rest maintain more frequently than the one replaced with (7 years ago). clamav rest version should be more frequently maintained one.
@ilodidoj  Kevin flagged this too, I am looking into other options

**Review by okkays — APPROVED** [review]
Good with this change to remove localstack

@ilodidoj We can discuss more in pairing - clamav is giving us trouble locally, but it's unrelated to this PR. If we manually fix clamav, we're able to upload / scan attachments locally using the local filesystem.

so, the proposal here is to go ahead and remove localstack and handle the clamav fixes as a separate task.

**Review by ilodidoj — APPROVED** [review]

**Pull request merged**
