### PR TITLE
Various and sundry a11y improvements!

### PR DESCRIPTION
**Pull request by el-mapache**
1). [Indicate the date format](https://github.com/18F/crt-portal/issues/282)
2). [Service members question not reading the labels](https://github.com/18F/crt-portal/issues/281)
3). [Details page isn't announcing 'words remaining' when typed](https://github.com/18F/crt-portal/issues/286)
4). [Screen reader error message on Details page doesn't match sighted experience](https://github.com/18F/crt-portal/issues/285)
5). [If there are multiple errors, all errors should get read by a screen reader](https://github.com/18F/crt-portal/issues/283)

## What does this change?
This PR rolls up a few smaller accessibility improvements! For more information, see the list above.
The numbered changes below correspond to the issue above 😄 

1). Wrap the `incident date` fields in a `section` element, and add the `aria-labelledby` attribute. This allows for the `em` help text to be read when the user first tabs into a date field. Subsequent date fields will not repeat the information; hopefully this provides enough context to the user without being overwhelming. This PR also adds a formatting hint to the `incident date` group.

2). Clean up the HTML by adding a missing opening `fieldset` tag, removing an extraneous div, and removing an unnecessary `margin` class. Also removes extra `label` element that was causing help text to be read out of order. As above, applied `aria-labelledby` to the parent div of the form elements, so help text is only read when the user first enters the field group

3). Word count announcement updates as user begins typing each word. The only change from the previous behavior is that we no longer reset the `aria-live` attribute to `polite` every time we _don't_ set `aria-live` to `assertive`; I think this repeated update may have been stopping the announcement.

4). Remove screen reader specific text from word limit JS

5). Screen readers will now read multiple error messages when the user enters the page.

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] Check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Overall it looks good!
 - I am not getting the help text for month on voicer over or the question for service members, maybe I am doing it wrong?
- I think the backend views are reading correctly. I missed that session with Terry, so @Jacklynn can be a second set of ears when this gets to dev

✅ words remaining is working
✅ got multiple error messages

**Comment by el-mapache** [comment]
@LindsayYoung Can you say some more about the steps you are taking when you don't hear the service member question? When I tab into the field, both the primary and help text are being read. I'm using safari + VO, Terri has indicated that's the most common set up for mac users. Chrome is super inconsistent in its Mac VO support.

**Comment by el-mapache** [comment]
@LindsayYoung The backend view are still be not fully supported; this PR only addresses the issues we surfaced in the public-facing form. The intake a11y fixes are coming in an upcoming PR!

**Comment by LindsayYoung** [comment]
I was testing with chrome, I can test with Safari next

**Pull request merged**
