### PR TITLE
Update HCE content in the rerouting guide

### PR DESCRIPTION
**Pull request by kewitham**
## What does this change?
This PR updates the content in the second page of the portal form for the housing and commercial or public location sections.

## Screenshots (for front-end PR):

image

image

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [x] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by okkays — APPROVED** [review]
LGTM!

It might make sense to put these screenshots on https://github.com/usdoj-crt/crt-portal-management/issues/1485 for signoff before merging.

**Review by ilodidoj — CHANGES_REQUESTED** [review]
@kewitham @okkays i think the changes are requested on card for Content routing guide for the intake specialist, not on the public facing pages. Please check internally again before merging.

**Comment by okkays** [comment]
@ilodidoj Good point, I think you're right and it was the internal form that needs the update.

**Review by okkays — CHANGES_REQUESTED** [review]
Agree with @ilodidoj, this should be in the internal routing guide.

**Comment by kewitham** [comment]
> 

@okkays @ilodidoj updated to only change the internal routing guide

**Review by okkays — APPROVED** [review]
Nice, thanks @kewitham!

**Review by ilodidoj — APPROVED** [review]
LGTM!! Nice work, @kewitham ready for merging to dev.

**Pull request merged**
