### PR TITLE
Add error class to text inputs

### PR DESCRIPTION
**Pull request by el-mapache**
[Link to ZenHub issue.](https://github.com/18F/crt-portal/issues/163)

## What does this change?
* Adds an error class to any required `input[type="text"]`, `textarea` or `select` field.
* Adds JS to clear the error border when content is changed.

## Screenshots (for front-end PR):
**HANDY GIF**:
error-ex

### Author

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] Check for [accessibility](/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.)
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Comment by Jacklynn** [comment]
1. @el-mapache is the red darker or is that just from the gif? I would expect the red to be the same as the icon.
2. YAYYYY!

**Comment by el-mapache** [comment]
@Jacklynn The red is going to be whatever it is defined as in `uswds`. Theoretically, if we were overriding that color in our stylesheet it should be reflected...to me though, it looks like the red is the same as the left border in our alert badge.

I can take a look tomorrow and double check. Which element should I be referencing for the correct hex code? The actual svg ! icon?

**Comment by Jacklynn** [comment]
I was expecting the red from the SVG icon, yes!

**Comment by el-mapache** [comment]
New border color to match svg fill color in alert error:

Screen Shot 2020-02-19 at 7 54 18 AM

**Comment by Jacklynn** [comment]
🚨😎

**Comment by LindsayYoung** [comment]
Gif is indeed handy! 

This ticket is scoped to the text boxes and that works. Out of scope but noting that required radio buttons are not in a red box but required checkboxes are in a red box.

**Pull request merged**
