### PR TITLE
Fix Long URLs when grouping by long descriptions

### PR DESCRIPTION
**Pull request by okkays**
Basically, replaces "violation_summary=report.description" with "violation_summary=report.id" for grouping mode.

This adds a lookup on the report id when filtering, but drastically reduces the length of the URL.

## What does this change?

- 🌎 We currently pass the full description as a filter when grouping.
- ⛔ This shows up in the URL, which causes URLs to be too long sometimes (greater than 8000 characters).
- ✅ This commit uses an arbitrary report id as the filter criteria, instead, meaning that the URL will stay small at the cost of one report lookup.

## Screenshots (for front-end PR):

GIF demonstrating that the URL is smaller now

### Author

+ [x] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [x] Check for, document, and establish a testing plan for any behavior that may vary across environments or is otherwise difficult to test.
+ [x] Check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [x] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

### Reviewer

+ [ ] If this is a story, run locally and check to make sure all Acceptance Criteria are met. (If any criteria are unclear, ask about them.).
+ [ ] Check for any behavior that may vary across environments or is difficult to test, and ensure that it is well-understood, documented, and that there is a testing plan in place.
+ [ ] Re-check for [accessibility](https://github.com/usdoj-crt/crt-portal/blob/develop/docs/a11y_plan.md).
+ [ ] [Tests pass](https://github.com/USDOJ/crt-portal/#tests).

## Notes for reviewer:

See [PR instructions doc](https://github.com/usdoj/crt-portal/blob/master/docs/pull_requests.md) for full pull request review instructions.

### CODE REVIEW

**Review by ilodidoj — COMMENTED** [review]
@okkays please check the conflict on this branch.  I can review again tomorrow.

**Comment by kewitham** [comment]
The violation summary in the url is used on the individual report pages to reconstruct the query and allow users to page through all reports in the group. That is usually found here but now it's missing:
image

**Comment by kewitham** [comment]
It looks like this value isn't being pulled correctly - should say 17 in the case I was testing for the second button - 
image

**Review by kewitham — CHANGES_REQUESTED** [review]
Unfortunately because of the way urls are used to rebuild queries this has some unexpected side effects.

**Comment by okkays** [comment]
@kewitham I'm not able to reproduce those missing reports - what's the description you're trying to match against, and how many records have it?

Here's the feature working as expected:

descriptions-url

bulk actions

**Review by kewitham — APPROVED** [review]
lgtm!

**Pull request merged**
